language: python

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.9

install: 
  - pip install -q Django==$DJANGO_VERSION

script:
  - python setup.py install
  - python runtests.py
