# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
t:
    it:
        title: 'LabAdmin'
        home: 'index.html'
    en:
        title: 'LabAdmin'
        home: 'index_eng.html'

baseurl: "/LabAdmin/"
url: "https://officinearduinotorino.github.io/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

machines:
    - img: 3d_1.png
      category: stampanti
      title: stampa 3d
    - img: fresa_1.png
      category: fresa
      title: fresa
    - img: laser_1.png
      category: laser
      title: taglio laser
    - img: plotter_1.png
      category: cutter
      title: plotter
    - img: 3d_2.png
      category: stampanti
      title: stampa 3d
    - img: fresa_2.png
      category: fresa
      title: fresa
    - img: laser_2.png
      category: laser
      title: taglio laser
    - img: plotter_2.png
      category: cutter
      title: plotter
    - img: 3d_3.png
      category: stampanti
      title: stampa 3d
    - img: fresa_3.png
      category: fresa
      title: fresa
    - img: laser_3.png
      category: laser
      title: taglio laser
    - img: plotter_3.png
      category: cutter
      title: plotter
